environment:
  matrix:
  - PYTHON: C:\Python38-x64
    PIP: C:\Python38-x64\Scripts\pip
    TWINE: C:\Python38-x64\Scripts\twine

build: off

install:
- %PIP% install pipenv
- %PYTHON% -m pipenv install

test_script:
- %PYTHON% -m pipenv run tests/test_basic.py
- %PYTHON% -m pipenv run tests/test_single_spin.py
