environment:
  matrix:
  - PYTHON: C:\Python38-x64\python
    PIP: C:\Python38-x64\Scripts\pip
    TWINE: C:\Python38-x64\Scripts\twine

build: off

install:
- cmd: "%PIP% install tables numpy scipy matplotlib ase pandas"

test_script:
- cmd: "%PYTHON% run tests\\test_basic.py"
- cmd: "%PYTHON% run tests\\test_single_spin.py"
