environment:
  matrix:
  - PYTHON: C:\Python38-x64
    PIP: C:\Python38-x64\Scripts\pip
    TWINE: C:\Python38-x64\Scripts\twine

build: off

install:
- cmd: "%PIP% install pipenv"
- cmd: "python --version"
- cmd: "python -m pipenv install"

test_script:
- cmd: "%PYTHON% -m pipenv run tests/test_basic.py"
- cmd: "%PYTHON% -m pipenv run tests/test_single_spin.py"
